### ISSUE TITLE
Bug: support Android prior to API 19

### ISSUE THREAD

**Issue by niqdev** [openwebnet/openwebnet-android#1]
verify the following issue
```
java.lang.NoClassDefFoundError: java.util.Objects
	at com.github.openwebnet.view.device.DeviceListAdapter.<init>(DeviceListAdapter.java:73)
	at com.github.openwebnet.view.device.DeviceListFragment.onCreateView(DeviceListFragment.java:73)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1965)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1078)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1624)
	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
	at com.github.openwebnet.view.MainActivity.onStart(MainActivity.java:211)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1188)
	at android.app.Activity.performStart(Activity.java:5382)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2266)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
	at android.app.ActivityThread.access$700(ActivityThread.java:159)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5419)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by moreau-nicolas** [comment]
I just reproduced the bug this morning by running the app on an API-16 virtual device.

See http://docs.oracle.com/javase/7/docs/api/java/util/Objects.html :
```java.lang.Objects``` was added in Java 1.7.

On Android the class only exists starting with API 19. See http://developer.android.com/reference/java/util/Objects.html

I can think of a couple fixes for this:
1. update the ```minSdkVersion``` to 19
2. remove all Java 7 API calls from the code base

Either way I think we can rename this issue to "Bug: support Android prior to API 19". :-)

**Comment by niqdev** [comment]
I will use [Preconditions](https://github.com/google/guava/wiki/PreconditionsExplained), we already have Guava dependency, I will add it explicitly in `build.gradle`

**Comment by niqdev** [comment]
This [commit](https://github.com/openwebnet/openwebnet-android/commit/54d771f672cb0753e57f06f0081b3506e0bf62cf) fixes `java.lang.NoClassDefFoundError: java.util.Objects`, but now we have this nice layout
<img width="377" alt="screen shot 2016-03-04 at 18 55 32" src="https://cloud.githubusercontent.com/assets/9458643/13535622/85500f3e-e23b-11e5-8b5d-1d8b0e113fb8.png">

**Comment by moreau-nicolas** [comment]
The branch moreau-nicolas/openwebnet-android@2a8c162ef27e9475acc9632c05edc5da51c7037f helps with removing the remaining NoClassDefFound exceptions (tested with Maven local repository).

@niqdev: I can't submit a PR untill openwebnet/rx-openwebnet#3 has been merged and a new version of rx-openwebnet has been released.

Meanwhile, I'll check this black rectangle thing.

**Comment by niqdev** [comment]
Well done, I forgot to check the library also! :disappointed_relieved:

**Comment by niqdev** [comment]
I've released `rx-openwebnet` version 0.7.2

**Comment by moreau-nicolas** [comment]
Thanks !

**Comment by niqdev** [comment]
I've merged few PRs so I don't actually know which one introduced this regression, but could you verify if you have the same problem, i.e. huge margin between cards? Thanks
![screen shot 2016-03-06 at 17 13 38](https://cloud.githubusercontent.com/assets/9458643/13555364/10996db8-e3bf-11e5-87bc-fe0b5bc14bde.png)

**Comment by moreau-nicolas** [comment]
Yes, I got it too. :(
Do you want me to investigate ?

**Comment by niqdev** [comment]
Yes please! Sorry I will delete the comment on the other card and I will close the issue again.
I've just opened a new [issue](https://github.com/openwebnet/openwebnet-android/issues/33)
Thanks

**Comment by niqdev** [comment]
I will fix the maxWidth for light and automation:

![screen shot 2016-03-06 at 18 23 21](https://cloud.githubusercontent.com/assets/9458643/13555734/aae5bb5c-e3c8-11e5-9b44-e033dad51c09.png)

**Comment by niqdev** [comment]
This [commit](https://github.com/openwebnet/openwebnet-android/commit/38fe1e8377265a1261b5dbb636b76b5f39278fbf) fixes the maxWidth

**Comment by moreau-nicolas** [comment]
I think we can close this issue: everything runs as expected on API 16, which is the documented ```minSdkVersion``` in the Manifest.
