### ISSUE TITLE
Crash due to secure-preferences lib

### ISSUE THREAD

**Issue by niqdev** [openwebnet/openwebnet-android#82]
v0.1.6 of [scottyab/secure-preferences](https://github.com/scottyab/secure-preferences) solved the [issue](https://github.com/scottyab/secure-preferences/issues/38), the problem is that the libs are incompatible after upgrading the version

Consider migration to alternative libs
* https://github.com/afiqiqmal/SharedChamber

old
* https://github.com/BottleRocketStudios/Android-Vault
* https://github.com/ophio/secure-preferences

```java
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:5750)
  at android.app.ActivityThread.-wrap1 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1656)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6501)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: 
  at com.google.common.base.CharMatcher$None.trimTrailingFrom (CharMatcher.java:1290)
  at com.google.common.io.BaseEncoding.decodeChecked (BaseEncoding.java:226)
  at com.google.common.io.BaseEncoding.decode (BaseEncoding.java:212)
  at com.github.openwebnet.database.DatabaseRealmConfig.getRealmKey (DatabaseRealmConfig.java:117)
  at com.github.openwebnet.database.DatabaseRealmConfig.getEncryptedConfig (DatabaseRealmConfig.java:86)
  at com.github.openwebnet.database.DatabaseRealmConfig.getConfig (DatabaseRealmConfig.java:72)
  at com.github.openwebnet.database.DatabaseRealm.setup (DatabaseRealm.java:29)
  at com.github.openwebnet.OpenWebNetApplication.initRealm (OpenWebNetApplication.java:31)
  at com.github.openwebnet.OpenWebNetApplication.onCreate (OpenWebNetApplication.java:22)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1120)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:5747)
```

**Comment by niqdev** [comment]
While testing on the emulator, after a version change from `3.1.0` to `3.1.1`, I was able to reproduce a bug caused by the same library that some user have already experienced and cause the app to be completly unusable

```
01-01 17:46:23.490 3306-3306/com.github.openwebnet E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.openwebnet, PID: 3306
    java.lang.RuntimeException: Unable to create application com.github.openwebnet.OpenWebNetApplication: java.lang.IllegalArgumentException: The provided key must be 64 bytes. Yours was: 0
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4521)
        at android.app.ActivityThread.access$1500(ActivityThread.java:144)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.IllegalArgumentException: The provided key must be 64 bytes. Yours was: 0
        at io.realm.RealmConfiguration$Builder.encryptionKey(RealmConfiguration.java:554)
        at com.github.openwebnet.database.DatabaseRealmConfig.getEncryptedConfig(DatabaseRealmConfig.java:86)
        at com.github.openwebnet.database.DatabaseRealmConfig.getConfig(DatabaseRealmConfig.java:72)
        at com.github.openwebnet.database.DatabaseRealm.setup(DatabaseRealm.java:29)
        at com.github.openwebnet.OpenWebNetApplication.initRealm(OpenWebNetApplication.java:31)
        at com.github.openwebnet.OpenWebNetApplication.onCreate(OpenWebNetApplication.java:22)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
        at android.app.ActivityThread.access$1500(ActivityThread.java:144) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5221) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
01-01 17:46:23.491 1528-2848/system_process W/ActivityManager:   Force finishing activity com.github.openwebnet/.view.MainActivity
```

`DatabaseRealmConfig#getRealmKey` crash because the key is the default value, and the reason is that `SecurePreferences#decrypt` fails on `AesCbcWithIntegrity.decryptString(cipherTextIvMac, keys)` with error
```
"MAC stored in civ does not match computed MAC."
```

**Comment by niqdev** [comment]
[Issue](https://github.com/scottyab/secure-preferences/issues/88) related to this bug

**Comment by niqdev** [comment]
After the latest release, lots reports of this issue like

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:5950)
  at android.app.ActivityThread.access$1200 (ActivityThread.java:200)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1673)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:201)
  at android.app.ActivityThread.main (ActivityThread.java:6806)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:873)
Caused by: java.lang.IllegalArgumentException: 
  at io.realm.RealmConfiguration$Builder.encryptionKey (RealmConfiguration.java:554)
  at com.github.openwebnet.database.DatabaseRealmConfig.getEncryptedConfig (DatabaseRealmConfig.java:86)
  at com.github.openwebnet.database.DatabaseRealmConfig.getConfig (DatabaseRealmConfig.java:72)
  at com.github.openwebnet.database.DatabaseRealm.setup (DatabaseRealm.java:29)
  at com.github.openwebnet.OpenWebNetApplication.initRealm (OpenWebNetApplication.java:31)
  at com.github.openwebnet.OpenWebNetApplication.onCreate (OpenWebNetApplication.java:22)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1155)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:5945)
```

Current solution is to remove this library

**Comment by niqdev** [comment]
In version `3.4.0` this library has been removed from the app and kept only for migration purposes and retrocompatibility.
